# Generated by Django 4.2.9 on 2024-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blackcoffer",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
