# Generated by Django 4.2.9 on 2024-02-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_blackcoffer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blackcoffer",
            name="id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
