# Generated by Django 4.2.9 on 2024-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_blackcoffer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blackcoffer",
            name="added",
            field=models.TextField(default="unknown", max_length=40),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="country",
            field=models.TextField(default="unknown", max_length=40),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="end_year",
            field=models.TextField(default="unknown", max_length=4),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="impact",
            field=models.TextField(default="unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="insight",
            field=models.TextField(default="unknown", max_length=150),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="intensity",
            field=models.TextField(default="unknown", max_length=3),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="likelihood",
            field=models.TextField(default="unknown", max_length=3),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="pestle",
            field=models.TextField(default="unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="published",
            field=models.TextField(default="unknown", max_length=40),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="region",
            field=models.TextField(default="unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="relevance",
            field=models.TextField(default="unknown", max_length=3),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="sector",
            field=models.TextField(default="unknown", max_length=30),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="source",
            field=models.TextField(default="unknown", max_length=200),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="start_year",
            field=models.TextField(default="unknown", max_length=4),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="title",
            field=models.TextField(default="unknown", max_length=500),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="topic",
            field=models.TextField(default="unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="blackcoffer",
            name="url",
            field=models.TextField(default="unknown", max_length=500),
        ),
    ]
